server:
  port: 8000

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cxggdv96v8hn.ap-northeast-2.rds.amazonaws.com/donaDB?autoReconnect=true
    username: master
    password: master456123
    driver-class-name: com.mysql.cj.jdbc.Driver